### ISSUE TITLE
希望添加自动缩放到游戏界面

### ISSUE THREAD

**Issue by EinhartStratos** [poooi/plugin-new-window#2]
就像这个一样
https://github.com/muhiro/aigisWidget
大部分dmm游戏都是flash的，应该能识别到并且只显示flash，隐藏地址栏
这个功能好做么，不好做就算了，现在也是可用的

**Comment by KochiyaOcean** [comment]
考虑增加
不过地址栏同时兼职工具栏（比如静音按钮也在它上面）所以是不会隐藏的

**Comment by KochiyaOcean** [comment]
已经添加自动识别并定位到 flash 位置的按键，同时禁止滚动。
但是因为 flash 大小的参数无法传递到上级，所以窗口大小仍然需要自己调整……

**Comment by KochiyaOcean** [comment]
增加了一个手动设置分辨率的选项以满足强迫症……
