### ISSUE TITLE
疑似的JS加载错误

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-new-window#3]
使用的是岛风go
![qq 20150917192333](https://cloud.githubusercontent.com/assets/12459199/9930936/349e5bd4-5d72-11e5-9136-cc9f67d962a6.png)

同代理下chrome  表现良好，应该和网络无关。
![qq 20150917192402](https://cloud.githubusercontent.com/assets/12459199/9930900/01a52744-5d72-11e5-8978-6b6de78129ff.png)

**Comment by KochiyaOcean** [comment]
打开开发者工具确认元素加载情况吧……除了网络问题以外我还真没想到别的可能性

**Comment by wafer-li** [comment]
SB了，没看到那里有个开发者工具。
![qq 20150918031013](https://cloud.githubusercontent.com/assets/12459199/9941831/ca4ce25a-5db2-11e5-8d50-9cb19e26e060.png)
看了一下那个文件，没分行结果一团乱。。。。

**Comment by KochiyaOcean** [comment]
http://help.cnzz.com/adm/course/case/2013/1012/328.html
cnzz.js 并非 DMM 页面上的元素，可能是由于 DNS 污染等原因导致的
附上正常加载的页面
![image](https://cloud.githubusercontent.com/assets/8194131/9941909/dc385768-5daa-11e5-9e0e-5b165c053a39.png)

**Comment by wafer-li** [comment]
所以是 Chrome 的插件问题？

**Comment by wafer-li** [comment]
删了几个插件，更新了一下岛风go，重启了程序之后就正常了。
也不知道是哪的问题。。。
