### ISSUE TITLE
開其他DMM遊戲出現錯誤（文豪とアルケミスト）

### ISSUE THREAD

**Issue by izumimizuyu** [poooi/plugin-new-window#9]
win8.1 64x poi v7.3.0
我開的是文豪とアルケミスト，poi有設定DMM地區cookie
![default](https://cloud.githubusercontent.com/assets/24191178/22577394/64212b76-e9fc-11e6-8d4e-2077604ebb12.png)
只有遊戲本體的那一區出了問題…拜託了orz

**Comment by KagamiChan** [comment]
这游戏检测 User Agent，只能在 chrome 或者 edge 上玩
虽然可以通过 user agent 伪装过去

**Comment by KochiyaOcean** [comment]
@KagamiChan

**Comment by KochiyaOcean** [comment]
@KagamiChan 有提供修改 UA 的方法，加一下就行了

**Comment by KagamiChan** [comment]
暂时的手段是点击一心二用右下角的齿轮状按钮，打开开发者工具，在 console 里面输入
```
 $('webview').setUserAgent('Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36')
```
并回车执行
这个就能绕过 UA 检测，不够不排除游戏还有别的检测是否是指定浏览器的方式，只能说风险自担了

**Comment by izumimizuyu** [comment]
啊哈哈…只好看DMM會不會有其他手法了…如果真被(嗶---)只好認命
終於不用被F5提示煩，或是手殘按到其他東西了，感謝兩位

**Comment by KagamiChan** [comment]
2.6 版本添加了模拟 UA 的选项

ref: poooi/poi#1376

**Comment by KochiyaOcean** [comment]
@KagamiChan 不，是强制钦点为 Chrome 的 UA
